export const books = [
  {
    id: 1,
    title: " In Search of Lost Time",
    author: "Marcel Proust",
    publisher: "HarperCollins",
    year: 1960,
    image: "https://d3i5mgdwi2ze58.cloudfront.net/ohbd3xqukj7do2f0o5txmhghfsva",
    price: 9.99,
    category: "read",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    publisher: "Penguin Books",
    year: 1949,
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
    price: 8.99,
    category: "currently reading",
  },
  {
    id: 3,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publisher: "Little, Brown and Company",
    year: 1951,
    image:
      "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91HPG31dTwL.jpg",
    price: 10.99,
    category: "want to read",
  },
  {
    id: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publisher: "Scribner",
    year: 1925,
    image: "https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg",
    price: 7.99,
    category: "want to read",
  },
  {
    id: 5,
    title: "Brave New World",
    author: "Aldous Huxley",
    publisher: "Harper Perennial Modern Classics",
    year: 1932,
    image:
      "https://pagdandi.org/wp-content/uploads/2021/04/Brave-New-World.jpg",
    price: 12.99,
    category: "currently reading",
  },
  {
    id: 6,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publisher: "Penguin Classics",
    year: 1813,
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL.jpg",
    price: 6.99,
    category: "read",
  },
  {
    id: 7,
    title: " Hamlet",
    author: "William Shakespeare",
    publisher: "Penguin Classics",
    year: 1813,
    image: "https://d3i5mgdwi2ze58.cloudfront.net/2rdow3iqvuw1qhjvxf527isb7i7h",
    price: 6.99,
    category: "none",
  },
  {
    id: 8,
    title: " Ulysses",
    author: "James Joyce",
    publisher: "Penguin Classics",
    year: 1813,
    image: "https://d3i5mgdwi2ze58.cloudfront.net/f7nkbyqfsnrrlct3hs01jkrz2vdi",
    price: 6.99,
    category: "none",
  },
  {
    id: 9,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    publisher: "Penguin Classics",
    year: 1813,
    image: "https://d3i5mgdwi2ze58.cloudfront.net/gvx0r9lfgd8w3mm2ef7vssyi2aaz",
    price: 6.99,
    category: "none",
  },
];
